"""Case export adapters (Community edition).

Community ships the *free* Markdown export plus a hard *block* for the premium
PDF export. The real PDF rendering lives in the separate ``threatforge-enterprise``
package, which overrides :func:`render_case_pdf`. The Community codebase must
never contain the premium implementation — only this adapter seam.

Security: the Markdown body escapes every user-controllable field, and the
exporter deliberately exposes *no* secrets — no ``storage_key``, no local file
paths, no tokens, and no evidence binaries (metadata only).
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from app.features import EnterpriseFeatureRequired, Feature


# Characters that could alter document structure or inject markup when the .md
# is later rendered to HTML. Escaped defensively.
_MD_SPECIAL = set("\\`*_{}[]()#+!|<>")


def md_escape(value) -> str:
    """Escape Markdown/HTML-significant characters in user-controllable text."""
    if value is None:
        return ""
    out = []
    for ch in str(value):
        if ch == "\r":
            continue
        if ch in _MD_SPECIAL:
            out.append("\\" + ch)
        else:
            out.append(ch)
    return "".join(out)


def _dt(value) -> str:
    if value is None:
        return ""
    return str(value)[:16].replace("T", " ")


def _block(lines, text, prefix):
    for line in (str(text or "").splitlines() or [""]):
        lines.append(prefix + md_escape(line))


def render_case_markdown(case, notes, evidence, edition: str = "community") -> str:
    """Build the free Markdown report. ``notes``/``evidence`` are ORM rows.

    Only metadata is emitted for evidence — never the binary, ``storage_key`` or
    any filesystem path.
    """
    L: list[str] = []
    L.append(f"# Case #{case.id} — {md_escape(case.title)}")
    L.append("")

    L.append("## Metadata")
    L.append("")
    L.append(f"- **Status:** {md_escape(case.status)}")
    L.append(f"- **Severity:** {md_escape(case.severity)}")
    L.append(f"- **Created:** {md_escape(_dt(case.created_at))}")
    if getattr(case, "closed_at", None):
        L.append(f"- **Closed:** {md_escape(_dt(case.closed_at))}")
    assignee = case.assignee_user_id
    L.append(f"- **Assignee:** {('user #' + md_escape(assignee)) if assignee is not None else '—'}")

    if getattr(case, "description", None):
        L.append("")
        L.append("## Description")
        L.append("")
        _block(L, case.description, "> ")

    snap = getattr(case, "finding_snapshot", None) or None
    L.append("")
    L.append("## Finding snapshot")
    L.append("")
    if snap:
        L.append(f"- **Domain:** {md_escape(snap.get('domain', ''))}")
        L.append(f"- **Score:** {md_escape(snap.get('score', ''))}")
        L.append(f"- **Verdict:** {md_escape(snap.get('verdict', ''))}")
        if snap.get("source"):
            L.append(f"- **Source:** {md_escape(snap.get('source'))}")
        if case.finding_id is None:
            L.append("- _Finding removed from live data — snapshot preserved for chain of custody._")
    else:
        L.append("_No finding linked._")

    L.append("")
    L.append(f"## Notes ({len(notes)})")
    L.append("")
    if notes:
        for n in notes:
            author = n.author_user_id
            head = f"- **{md_escape(_dt(n.created_at))}** · {('user #' + md_escape(author)) if author is not None else '—'}"
            if getattr(n, "is_internal", False):
                head += " · internal"
            L.append(head)
            _block(L, n.body, "  > ")
    else:
        L.append("_No notes._")

    L.append("")
    L.append(f"## Evidence ({len(evidence)})")
    L.append("")
    if evidence:
        for e in evidence:
            stored = (e.storage_backend == "local" and bool(e.storage_key))
            up = e.uploaded_by_user_id
            L.append(f"- **{md_escape(e.filename)}** — {md_escape(e.mime_type)} · "
                     f"{int(e.size_bytes or 0)} bytes · origin: {md_escape(e.origin)}")
            L.append(f"  - sha256: `{md_escape(e.sha256)}`")
            L.append(f"  - uploaded by {('user #' + md_escape(up)) if up is not None else '—'} · "
                     f"{md_escape(_dt(e.created_at))} · {'stored' if stored else 'metadata-only'}")
            if e.description:
                L.append(f"  - note: {md_escape(e.description)}")
    else:
        L.append("_No evidence._")

    L.append("")
    L.append("---")
    L.append(f"_Generated by ThreatForge ({md_escape(edition)}) · {md_escape(_dt(datetime.now(timezone.utc)))} UTC_")
    L.append("")
    return "\n".join(L)


def _case_report(case, edition: str = "community", **_) -> dict:
    """Non-secret report payload for the Enterprise PDF renderer.

    No secrets: no storage keys, no file paths, no evidence binaries — only case
    metadata the analyst already sees.
    """
    cid = getattr(case, "id", "")
    title = getattr(case, "title", None) or f"Investigation Case {cid}"
    findings: list[dict] = []
    snap = getattr(case, "finding_snapshot", None)
    if isinstance(snap, dict):
        findings.append({
            "title": str(snap.get("domain") or snap.get("title") or "finding"),
            "severity": str(getattr(case, "severity", "") or ""),
            "summary": "",
        })
    return {
        "tenant_name": str(getattr(case, "tenant_id", "") or ""),
        "report_title": str(title),
        "executive_summary": f"Investigation case #{cid} ({getattr(case, 'status', '')}).",
        "risk_score": int(getattr(case, "risk_score", 0) or 0),
        "findings": findings,
        "report_id": f"case-{cid}",
    }


def render_case_pdf(case, **kwargs) -> bytes:
    """Premium case PDF. Community/unlicensed -> HTTP 402.

    Formal path: gate via the feature layer, then delegate the actual rendering to
    the Enterprise package through :mod:`app.enterprise_adapter`. No premium code
    lives here, and Community never imports the Enterprise package directly.
    """
    from app import enterprise_adapter, features
    features.ensure_enabled(features.Feature.EXPORT_PDF)
    return enterprise_adapter.generate_case_pdf(_case_report(case, **kwargs))


# ---------------------------------------------------------------------------
# STIX 2.1 (partial) — export LOCAL de um case. Community, gratuito.
# Sem chamadas de rede, sem secrets, sem storage_key/paths: apenas indicadores
# (domínio do finding + hashes SHA-256 das evidências) + report do case.
# ---------------------------------------------------------------------------

_VERDICT_INDICATOR_TYPE = {
    "malicious": "malicious-activity",
    "suspicious": "anomalous-activity",
    "low": "benign",
    "no_known_threat": "benign",
    "info": "unknown",
}


def _stix_ts(value=None) -> str:
    """Timestamp STIX (UTC, milissegundos, sufixo Z)."""
    if value is None:
        dt = datetime.now(timezone.utc)
    elif isinstance(value, datetime):
        dt = value
    else:  # string ISO já formatada — normaliza o "T"/sufixo de forma simples
        txt = str(value).replace(" ", "T")
        if not txt.endswith("Z") and "+" not in txt:
            txt = txt.split(".")[0] + ".000Z"
        return txt
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")


def _stix_str(value) -> str:
    """Escapa valor para dentro de um padrão STIX (aspas simples)."""
    return str(value or "").replace("\\", "\\\\").replace("'", "\\'")


def _verdict_indicator_type(verdict) -> str:
    return _VERDICT_INDICATOR_TYPE.get(str(verdict or "").lower(), "unknown")


def _new_id(kind: str) -> str:
    return f"{kind}--{uuid.uuid4()}"


def render_case_stix_bundle(case, evidence, producer_name: str = "ThreatForge") -> dict:
    """Monta um STIX 2.1 bundle (partial) a partir do case.

    Objetos: identity (produtor), report (case), indicators (domínio do finding
    e hashes SHA-256 das evidências). Nada de secrets, caminhos ou rede.
    """
    now = _stix_ts()
    identity_id = _new_id("identity")
    identity = {
        "type": "identity", "spec_version": "2.1", "id": identity_id,
        "created": now, "modified": now,
        "name": producer_name or "ThreatForge", "identity_class": "system",
    }

    indicators: list[dict] = []
    refs: list[str] = []

    snap = getattr(case, "finding_snapshot", None) or {}
    domain = snap.get("domain")
    if domain:
        ind = {
            "type": "indicator", "spec_version": "2.1", "id": _new_id("indicator"),
            "created": now, "modified": now, "created_by_ref": identity_id,
            "name": f"Suspicious domain {domain}",
            "pattern": "[domain-name:value = '%s']" % _stix_str(domain),
            "pattern_type": "stix",
            "valid_from": _stix_ts(getattr(case, "created_at", None)),
            "indicator_types": [_verdict_indicator_type(snap.get("verdict"))],
        }
        score = snap.get("score")
        try:
            if score is not None:
                ind["confidence"] = max(0, min(100, int(score)))
        except (TypeError, ValueError):
            pass
        indicators.append(ind)
        refs.append(ind["id"])

    for e in evidence:
        if not getattr(e, "sha256", None):
            continue
        ind = {
            "type": "indicator", "spec_version": "2.1", "id": _new_id("indicator"),
            "created": now, "modified": now, "created_by_ref": identity_id,
            "name": f"Evidence file {e.filename}",
            "pattern": "[file:hashes.'SHA-256' = '%s']" % _stix_str(e.sha256),
            "pattern_type": "stix",
            "valid_from": _stix_ts(getattr(e, "created_at", None)),
            "indicator_types": ["unknown"],
        }
        indicators.append(ind)
        refs.append(ind["id"])

    report = {
        "type": "report", "spec_version": "2.1", "id": _new_id("report"),
        "created": now, "modified": now, "created_by_ref": identity_id,
        "name": case.title or f"Case #{case.id}",
        "published": _stix_ts(getattr(case, "created_at", None)),
        "report_types": ["threat-report"],
        # object_refs não pode ser vazio: referencia a identity quando não há indicadores
        "object_refs": refs or [identity_id],
    }
    if getattr(case, "description", None):
        report["description"] = str(case.description)

    objects = [identity, report] + indicators
    return {"type": "bundle", "id": _new_id("bundle"), "objects": objects}


# ---------------------------------------------------------------------------
# Credential Intelligence — dossiê por identidade (Markdown / PDF premium)
# ---------------------------------------------------------------------------
def render_credential_markdown(ident: dict, findings: list, related: list,
                               events: list, edition: str = "community") -> str:
    """Dossiê de identidade em Markdown. NUNCA inclui senha em claro (os findings
    já vêm redigidos: só password_sha256/máscara). E-mails já mascarados por role."""
    L = []
    L.append(f"# Credential dossier — {md_escape(ident.get('email'))}")
    L.append("")
    L.append("## Summary")
    L.append("")
    L.append(f"- **Domain:** {md_escape(ident.get('domain') or '')}")
    L.append(f"- **VIP:** {'yes' if ident.get('vip_asset_id') else 'no'}")
    L.append(f"- **Leaks:** {md_escape(ident.get('leak_count'))}")
    L.append(f"- **Unique passwords:** {md_escape(ident.get('unique_passwords'))}")
    L.append(f"- **Max risk:** {md_escape(ident.get('max_risk'))}/100")
    L.append(f"- **Password reuse:** {md_escape(ident.get('reuse_count', 0))} "
             f"(+{md_escape(ident.get('reuse_risk', 0))} risk)")
    if ident.get("sources"):
        L.append(f"- **Sources:** {md_escape(', '.join(ident['sources']))}")
    if ident.get("stealer_families"):
        L.append(f"- **Stealer families:** {md_escape(', '.join(ident['stealer_families']))}")

    L.append("")
    L.append(f"## Leaks ({len(findings)})")
    L.append("")
    if findings:
        for f in findings:
            det = f.get("detail") or {}
            parts = [f"{md_escape(k)}: {md_escape(v)}" for k, v in det.items() if k != "risk_breakdown"]
            L.append(f"- **{md_escape(f.get('source'))}** · {md_escape((f.get('created_at') or '')[:16])} · "
                     f"risk {md_escape(f.get('risk_score'))}")
            if parts:
                L.append(f"  - {'; '.join(parts)}")
    else:
        L.append("_No leaks._")

    L.append("")
    L.append(f"## Related identities (password reuse) ({len(related)})")
    L.append("")
    if related:
        for r in related:
            L.append(f"- {md_escape(r.get('email'))} · leaks {md_escape(r.get('leak_count'))}")
    else:
        L.append("_None._")

    L.append("")
    L.append(f"## Timeline ({len(events)})")
    L.append("")
    if events:
        for e in events:
            L.append(f"- **{md_escape((e.get('ts') or '')[:16])}** · {md_escape(e.get('type'))} — {md_escape(e.get('title'))}")
    else:
        L.append("_No events._")

    L.append("")
    L.append("---")
    L.append(f"_Generated by ThreatForge ({md_escape(edition)}) · no plaintext credentials by design._")
    L.append("")
    return "\n".join(L)


def _credential_report(ident, findings=None, related=None, events=None,
                       edition: str = "community", **_) -> dict:
    """Non-secret report payload for a credential dossier PDF.

    ``ident`` is the **already role-masked** dossier dict produced by the route
    (same as export.md/.json), NOT the raw ORM object — so a viewer never gets
    the full e-mail. Never includes plaintext passwords/cookies/tokens or full
    password hashes; ``findings`` arrive redacted/masked from the route.
    """
    if isinstance(ident, dict):
        ihash = str(ident.get("identity_hash") or ident.get("id") or "")
        subject = str(ident.get("email") or ihash)   # masked upstream by role
        risk = int(ident.get("max_risk") or 0)
        leaks = ident.get("leak_count") or 0
    else:  # defensive fallback; routes always pass the masked dict
        ihash = str(getattr(ident, "identity_hash", "") or "")
        subject = str(getattr(ident, "email", "") or ihash)
        risk = int(getattr(ident, "max_risk", 0) or 0)
        leaks = getattr(ident, "leak_count", 0) or 0
    return {
        "tenant_name": str((ident.get("tenant_id") if isinstance(ident, dict)
                            else getattr(ident, "tenant_id", "")) or ""),
        "report_title": "Credential Exposure Dossier",
        "executive_summary": "Aggregated credential exposure (redacted; no plaintext secrets).",
        "risk_score": risk,
        "findings": [{
            "title": subject,
            "severity": "",
            "summary": f"leaks={leaks}; sources={len(findings or [])}",
        }],
        "report_id": f"cred-{ihash[:12]}",
    }


def render_credential_pdf(ident, findings=None, related=None, events=None,
                          **kwargs) -> bytes:
    """Premium credential-dossier PDF. Community/unlicensed -> HTTP 402.

    ``ident`` must be the role-masked dossier dict (see the route). Same formal,
    adapter-mediated path as :func:`render_case_pdf`.
    """
    from app import enterprise_adapter, features
    features.ensure_enabled(features.Feature.EXPORT_PDF)
    return enterprise_adapter.generate_credential_pdf(
        _credential_report(ident, findings=findings, related=related,
                           events=events, **kwargs))
