"""Case export adapters (Community edition).

Community ships the *free* Markdown export plus a hard *block* for the premium
PDF export. The real PDF rendering lives in the separate ``threatforge-enterprise``
package, which overrides :func:`render_case_pdf`. The Community codebase must
never contain the premium implementation — only this adapter seam.

Security: the Markdown body escapes every user-controllable field, and the
exporter deliberately exposes *no* secrets — no ``storage_key``, no local file
paths, no tokens, and no evidence binaries (metadata only).
"""
from __future__ import annotations

from datetime import datetime, timezone


class EnterpriseFeatureRequired(Exception):
    """Raised by Community adapters for features gated to Enterprise."""

    feature = "pdf_export"


# Characters that could alter document structure or inject markup when the .md
# is later rendered to HTML. Escaped defensively.
_MD_SPECIAL = set("\\`*_{}[]()#+!|<>")


def md_escape(value) -> str:
    """Escape Markdown/HTML-significant characters in user-controllable text."""
    if value is None:
        return ""
    out = []
    for ch in str(value):
        if ch == "\r":
            continue
        if ch in _MD_SPECIAL:
            out.append("\\" + ch)
        else:
            out.append(ch)
    return "".join(out)


def _dt(value) -> str:
    if value is None:
        return ""
    return str(value)[:16].replace("T", " ")


def _block(lines, text, prefix):
    for line in (str(text or "").splitlines() or [""]):
        lines.append(prefix + md_escape(line))


def render_case_markdown(case, notes, evidence, edition: str = "community") -> str:
    """Build the free Markdown report. ``notes``/``evidence`` are ORM rows.

    Only metadata is emitted for evidence — never the binary, ``storage_key`` or
    any filesystem path.
    """
    L: list[str] = []
    L.append(f"# Case #{case.id} — {md_escape(case.title)}")
    L.append("")

    L.append("## Metadata")
    L.append("")
    L.append(f"- **Status:** {md_escape(case.status)}")
    L.append(f"- **Severity:** {md_escape(case.severity)}")
    L.append(f"- **Created:** {md_escape(_dt(case.created_at))}")
    if getattr(case, "closed_at", None):
        L.append(f"- **Closed:** {md_escape(_dt(case.closed_at))}")
    assignee = case.assignee_user_id
    L.append(f"- **Assignee:** {('user #' + md_escape(assignee)) if assignee is not None else '—'}")

    if getattr(case, "description", None):
        L.append("")
        L.append("## Description")
        L.append("")
        _block(L, case.description, "> ")

    snap = getattr(case, "finding_snapshot", None) or None
    L.append("")
    L.append("## Finding snapshot")
    L.append("")
    if snap:
        L.append(f"- **Domain:** {md_escape(snap.get('domain', ''))}")
        L.append(f"- **Score:** {md_escape(snap.get('score', ''))}")
        L.append(f"- **Verdict:** {md_escape(snap.get('verdict', ''))}")
        if snap.get("source"):
            L.append(f"- **Source:** {md_escape(snap.get('source'))}")
        if case.finding_id is None:
            L.append("- _Finding removed from live data — snapshot preserved for chain of custody._")
    else:
        L.append("_No finding linked._")

    L.append("")
    L.append(f"## Notes ({len(notes)})")
    L.append("")
    if notes:
        for n in notes:
            author = n.author_user_id
            head = f"- **{md_escape(_dt(n.created_at))}** · {('user #' + md_escape(author)) if author is not None else '—'}"
            if getattr(n, "is_internal", False):
                head += " · internal"
            L.append(head)
            _block(L, n.body, "  > ")
    else:
        L.append("_No notes._")

    L.append("")
    L.append(f"## Evidence ({len(evidence)})")
    L.append("")
    if evidence:
        for e in evidence:
            stored = (e.storage_backend == "local" and bool(e.storage_key))
            up = e.uploaded_by_user_id
            L.append(f"- **{md_escape(e.filename)}** — {md_escape(e.mime_type)} · "
                     f"{int(e.size_bytes or 0)} bytes · origin: {md_escape(e.origin)}")
            L.append(f"  - sha256: `{md_escape(e.sha256)}`")
            L.append(f"  - uploaded by {('user #' + md_escape(up)) if up is not None else '—'} · "
                     f"{md_escape(_dt(e.created_at))} · {'stored' if stored else 'metadata-only'}")
            if e.description:
                L.append(f"  - note: {md_escape(e.description)}")
    else:
        L.append("_No evidence._")

    L.append("")
    L.append("---")
    L.append(f"_Generated by ThreatForge ({md_escape(edition)}) · {md_escape(_dt(datetime.now(timezone.utc)))} UTC_")
    L.append("")
    return "\n".join(L)


def render_case_pdf(case, **kwargs) -> bytes:
    """Premium PDF export — NOT available in Community.

    The Enterprise package overrides this function with a real renderer. Here it
    only exposes the seam and refuses, leaking nothing about the Enterprise module.
    """
    raise EnterpriseFeatureRequired()
